engage/engage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('goal/', include('goal.urls')),
    path('admin/', admin.site.urls),
]

engage/goal/urls.py
from django.urls import path

from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.register, name='register'),
    path('<int:movie_id>/', views.detail, name='detail'),
    path('location/', views.location, name='location'),
    path('search/', views.search, name='search'),
    path('recommend/', views.recommend, name='recommend'),
]

engage/goal/models.py
from datetime import date
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class Users(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    email = models.EmailField()
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    phone = models.CharField(max_length=20)
    city = models.CharField(max_length=20)
    country = models.CharField(max_length=20)
    dob = models.DateField()

    def age(self) -> int:
        "Return the current age of this user."
        today = date.today()
        return today.year - self.dob.year - ((today.month, today.day) < (self.dob.month, self.dob.day))

    def __str__(self):
        return self.username


class Genre(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Keyword(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Movie(models.Model):
    color = models.CharField(max_length=100, null=True, blank=True)
    director_name = models.CharField(max_length=100)
    num_critic_for_reviews = models.IntegerField()
    duration = models.IntegerField()
    director_facebook_likes = models.IntegerField()
    actor_3_facebook_likes = models.IntegerField()
    actor_2_name = models.CharField(max_length=100)
    actor_1_facebook_likes = models.IntegerField()
    gross = models.IntegerField()
    genres = models.ManyToManyField(Genre)
    actor_1_name = models.CharField(max_length=100)
    movie_title = models.CharField(max_length=100)
    num_voted_users = models.IntegerField()
    cast_total_facebook_likes = models.IntegerField()
    actor_3_name = models.CharField(max_length=100)
    facenumber_in_poster = models.IntegerField()
    plot_keywords = models.ManyToManyField(Keyword)
    movie_imdb_link = models.CharField(max_length=100)
    num_user_for_reviews = models.IntegerField()
    language = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    content_rating = models.CharField(max_length=100)
    budget = models.IntegerField()
    title_year = models.IntegerField()
    actor_2_facebook_likes = models.IntegerField()
    imdb_score = models.FloatField()
    aspect_ratio = models.FloatField()
    movie_facebook_likes = models.IntegerField()
    popularity = models.FloatField()
    rated = models.ManyToManyField(Users, through='Rating')

    def age_limit(self) -> int:
        "Returns the minimum age required for this movie."
        return {
            'Approved': 0,
            'G': 2,
            'GP': 7,
            'PG': 10,
            'PG-13': 13,
            'Unrated': 14,
            'Not Rated': 15,
            'Passed': 15,
            'R': 16,
            'X': 17,
            'NC-17': 17,
            'M': 18
        }.get(self.content_rating, 18)

    class Meta:
        verbose_name_plural = 'Movies'
        ordering = ['movie_title']

    def __str__(self):
        return self.movie_title


class Rating(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(
        validators=[MaxValueValidator(5), MinValueValidator(0)]
    )

    class Meta:
        unique_together = ('user', 'movie')

    def __str__(self):
        return self.user.username + ' ' + self.movie.movie_title

engage/goal/views/views_movies.py
from django.shortcuts import get_object_or_404, render

from ..models import Movie, Users, Rating

import goal.utils.helper as helper
import goal.utils.recommender as recommender


def index(request):
    if 'mood' in request.GET:
        mood = request.GET.get('mood')
        genres = helper.getGenres(mood)
        user_age = Users.objects.get(username=request.user.username).age()
        allowed_ratings = helper.get_allowed_ratings(user_age)
        movies = Movie.objects.filter(
            genres__name__in=genres, content_rating__in=allowed_ratings).distinct()
        rec = movies.order_by('-popularity', '-imdb_score')[:300]
        # query = reduce(operator.and_, [Q(**{'genres__name__in': genres})])
        # movies = Movie.objects.filter(query)
        # print(movies.distinct().count())
        # return render(request, 'goal/index.html', {'movies': movies})
        context = {
            'movies': rec,
            'parameter': 'Mood'
        }
        return render(request, 'goal/recommend.html', context)
    else:
        print('no mood')
    return render(request, 'goal/index.html')


def search(request):
    if request.method == 'POST' and 'searchString' in request.POST:
        search = request.POST.get('searchString')

        user_age = Users.objects.get(username=request.user.username).age()
        allowed_ratings = helper.get_allowed_ratings(user_age)

        movies = recommender.search(search, allowed_ratings)
        context = {
            'movies': movies,
            'parameter': 'Search Query'
        }
        return render(request, 'goal/recommend.html', context)
    else:
        return render(request, 'goal/index.html')


def recommend(request):
    if request.method == 'POST':
        movie_id = request.POST.get('movie_id')
        movies = recommender.movie(movie_id)
        context = {
            'movies': movies,
            'parameter': 'Recommendation'
        }
        return render(request, 'goal/recommend.html', context)

    else:
        return render(request, 'goal/index.html')


def location(request):
    country = helper.get_country(request)
    print(country)
    movies = Movie.objects.filter(country=country).order_by(
        '-popularity', '-imdb_score')[:300]
    context = {
        'movies': movies,
        'parameter': 'Location'
    }
    return render(request, 'goal/recommend.html', context)


def detail(request, movie_id):
    rating = 0
    if request.method == 'POST':
        rating = int(request.POST.get('rating'))
    movie = get_object_or_404(Movie, id=movie_id)
    user = get_object_or_404(Users, username=request.user.username)
    allowed_ratings = helper.get_allowed_ratings(user.age())
    if not movie.content_rating in (allowed_ratings):
        return render(request, 'goal/index.html')
    print(movie)
    print(user)
    q = movie.rating_set.filter(user=user)
    print(q)
    ratingM = None
    if rating >= 1 and rating <= 5:
        if q.count() > 0:
            ratingM = q.first()
            ratingM.rating = rating
            print(rating)
            ratingM.save()
            movie.rating_set.add(ratingM)
            print('saved')
        else:
            ratingM = Rating(user=user, movie=movie, rating=rating)
            ratingM.save()
            movie.rating_set.add(ratingM)
            print('created')
    print(Rating.objects.all())
    context = {
        'movie': movie,
        'rating': ratingM
    }
    return render(request, 'goal/details.html', context)

engage/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />

    <script
      src="https://kit.fontawesome.com/564f21f8c6.js"
      crossorigin="anonymous"
    ></script>

    <title>Your Goal | {% block title %} {% endblock %}</title>
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    {% block styles %} {% endblock %}
  </head>
  <body>
    {% include 'partials/_navbar.html' %}
    <div class="bg-image"></div>
    <div class="container body-container" id="style-scroll">
      <div class="row body-row">
        <div class="col-md m-auto body-content">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

engage/templates/goal/details.html
{% extends 'base.html' %} {% block styles %} {% load static %}
<link rel="stylesheet" href="{% static 'css/details.css' %}" />
{% endblock %} {% block content %}
<div class="container vh-100 text-white mt-5">
  <div class="row">
    <div class="col-md-8"><h1>{{movie.movie_title}}</h1></div>
    <div class="col-md-4">
      {% comment %} {% if rating %} {% endcomment %}
      <div class="rating">
        <h3>
          <form
            method="post"
            action="{% url 'movies:detail' movie_id=movie.id %}"
          >
            {% csrf_token %}<span class="fs-5">Rating:</span> {% for i in '12345'|make_list %}
            <button
              type="submit"
              name="rating"
              value="{{i}}"
              class="btn {% if rating.rating > i|add:"-1" %} text-warning {% endif %} m-0 p-0"
            >
              <i class="fa fa-solid fa-heart fa-1x"></i>
            </button>
            {% endfor %}
          </form>
        </h3>
      </div>
      {% comment %} {% else %}
      <div class="rating">
        <h3>Rating: Not Rated</h3>
      </div>
      {% endif %} {% endcomment %}
    </div>
  </div>
  <div class="row">
    <div class="col-md my-3">
      {% for genre in movie.genres.all %}
      <button class="glow-on-hover px-2 mx-1">{{ genre }}</button>
      {% endfor %}
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <img
        src="https://picsum.photos/200/300"
        alt="{{movie.movie_title}}"
        class="img-fluid img-thumbnail mx-auto d-block"
      />
      <div class="row text-center">
        <div class="col-md-6 my-3">
          <h4>IMDB Rating:</h4>
          <i class="fa fa-solid fa-star fa-2x"></i
          ><span class="movie-rating"> {{movie.imdb_score}}</span>
        </div>
        <div class="col-md-6 my-3">
          <h4>Meta Score:</h4>
          <i class="fa fa-solid fa-thumbs-up fa-2x"></i
          ><span class="movie-rating"> {{movie.movie_facebook_likes}}</span>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <div class="row">
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum a
      reiciendis beatae sed suscipit corporis fuga quaerat soluta neque. Hic
      facilis aperiam commodi! Nihil, earum commodi ad tenetur corporis quos.
      Quisquam, quisquam. Lorem ipsum dolor sit amet consectetur adipisicing
      elit. Itaque nobis, provident sapiente repudiandae eum quas! Totam maiores
      laborum, repellat consequatur necessitatibus cumque facilis at sunt,
      repellendus non molestias laboriosam nihil?
      </div><br/>
      <div class="row">
        <div class="col">
        <div class="float-end fw-bold">
          <form method="post" action="{% url 'movies:recommend' %}">
            {% csrf_token %}
            <input type="hidden" name="movie_id" value="{{movie.id}}">
            <button class="recommend-button btn  btn-outline-light ">
              <i class="fa fa-solid fa-play"></i> Recommend Similar Movies
            </button>
          </form>
        </div>
        </div>
      </div>
      <div class="row">
        <div class="col my-3">
          <p>Cast &nbsp;<i class="icon-chevron fa fa-solid fa-chevron-right fa-beat-fade"></i></p>
        </div>
      </div>
      <div class="container">
        <div class="row">
        <div class="col-4 actor-card">
          <div class="row">
            <div class="col-4">
              <img class="img-fluid rounded-circle" src="https://i.pravatar.cc/70?u={{ movie.actor_1_name }}" alt="{{ user.get_short_name }}"/>
            </div>
            <div class="col-8">
              <h6 class="actor-name">{{ movie.actor_1_name }}</h6>
              <p class="text-muted">Actor</p>
            </div>
          </div>
        </div>
        <div class="col-4 actor-card">
          <div class="row">
            <div class="col-4">
              <img class="img-fluid rounded-circle" src="https://i.pravatar.cc/70?u={{ movie.actor_2_name }}" alt="{{ user.get_short_name }}"/>
            </div>
            <div class="col-8">
              <h6 class="actor-name">{{ movie.actor_2_name }}</h6>
              <p class="text-muted">Actor</p>
            </div>
          </div>
        </div>
        <div class="col-4 actor-card">
          <div class="row">
            <div class="col-4">
              <img class="img-fluid rounded-circle" src="https://i.pravatar.cc/70?u={{ movie.actor_3_name }}" alt="{{ user.get_short_name }}"/>
            </div>
            <div class="col-8">
              <h6 class="actor-name">{{ movie.actor_3_name }}</h6>
              <p class="text-muted">Actor</p>
            </div>
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>
<script src="{% static 'js/details.js' %}" type="text/javascript"></script>
{% endblock %}

engage/templates/goal/index.html
{% extends 'base.html' %} {% block content %} {% load static %}
<link rel="stylesheet" href="{% static 'css/faceDetect.css' %}" />
<div class="container-fluid mt-3">
  <video id="detectVideo" autoplay muted></video>
</div>
<script>
  var modelSrc = "{% static 'models' %}"
</script>
<script
  src="{% static '/js/face-api.min.js' %}"
  type="text/javascript"
></script>
<script src="{% static 'js/faceDetect.js' %}" type="text/javascript"></script>
{% endblock %}

engage/templates/goal/login.html
{% extends 'base.html' %} {% block content %}{% load static %}
<link rel="stylesheet" href="{% static 'css/login.css' %}" />
<div class="container mt-5 col-md-8">
  <div class="row my-5">
    <div class="col-md text-center text-light">
      <h1>Welcome to Movie Recommendations</h1>
    </div>
  </div>
  <form
    id="form1"
    class="form-signin"
    method="post"
    action="{% url 'movies:login' %}"
  >
    {% csrf_token %}
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-4 text-center mt-5">
          <label for="inputUserName" class="sr-only">Username</label>
          <input
            type="text"
            name="username"
            id="inputUserName"
            class="form-control input-text"
            placeholder="Username"
            required
            autofocus
          />
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="col-4 text-center mt-3">
          <label for="inputPassword" class="sr-only">Password</label>
          <input
            type="password"
            name="password"
            id="inputPassword"
            class="form-control input-text"
            placeholder="Password"
            required
          />
        </div>
      </div>
      <div class="row text-center">
        <h4>
          <a
            class="button-logout mt-5"
            href="javascript:;"
            onclick="document.getElementById('form1').submit();"
            >CLick here to login</a
          >
        </h4>
      </div>
      <p class="mt-5 mb-3 text-muted text-center">
        Don't have an account yet?
        <a class="register" href="{% url 'movies:register' %}">Register now</a>
      </p>
    </div>
  </form>
</div>
{% endblock %}

engage/templates/goal/logout.html
{% extends 'base.html' %} {% block content %}{% load static %}
<link rel="stylesheet" href="{% static 'css/logout.css' %}" />
<div class="container mt-5 col-md-6">
  <div class="row">
    <div class="col-md text-center text-light">
      <h1>You have been logged out.</h1>
      <p>Thank You for using the app.</p>
    </div>
  </div>
  <div class="row text-center">
    <h4>
      <a class="button-logout mt-5" href="{% url 'movies:login' %}"
        >CLick here to login again.</a
      >
    </h4>
  </div>
</div>
{% endblock %}

engage/templates/goal/recommend.html
{% extends 'base.html' %} {% block styles %} {% load static %}
<link rel="stylesheet" href="{% static 'css/recommend.css' %}" />
{% endblock %} {% block content %}
<div class="container vh-100 text-white mt-5">
  <div class="row">
    <div class="col-md">
      <h1>We got your {{ parameter }}!</h1>
      Our recommendations:
    </div>
  </div>
  <div class="row row-cols-3 my-1 rol-cols-md-2 g-5">
    {% for movie in movies %}
    <div class="col my-5">
      <div class="card h-100 bg-transparent position-relative">
        <a
          href="{% url 'movies:detail' movie.id %}"
          class="btn bg-transparent text-white"
        >
          <img
            loading="lazy"
            src="https://picsum.photos/seed/{{movie.id}}/300/400?a"
            class="card-img-top rounded"
            alt="{{movie.movie_title}}"
        /></a>

        <div
          class="btn-group glow-on-hover btn-group-sm position-absolute top-0 end-0"
        >
          <a
            href="{{ movie.movie_imdb_link }}"
            class="btn text-light"
            aria-current="page"
            ><i class="fa fa-solid fa-eye fa-1x"></i
          ></a>
          <a href="{{movie.movie_imdb_link}}" class="btn text-light"
            >{{movie.cast_total_facebook_likes}}</a
          >
        </div>
        <div class="card-body px-1">
          <h5 class="card-title m-0 text-white">{{ movie.movie_title }}</h5>
          <span class="card-text p-0 m-0">{{ movie.title_year }}</span>
          <span class="card-text p-0 text-muted m-0 h-4"
            >{{ movie.content_rating }}</span
          >
          <p class="card-text p-0 text-muted m-0">{{ movie.duration }} mins</p>
          <p class="card-text p-0 m-0">
            Keywords: {% for keyword in movie.plot_keywords.all %}
            <span class="badge bg-white-50 keyword-span" style="cursor: pointer"
              >{{ keyword }}</span
            >
            {% endfor %}
          </p>
        </div>
        <div class="card-footer"></div>
        <a
          href="{% url 'movies:detail' movie.id %}"
          class="btn bg-transparent text-white"
          >View movie</a
        >
      </div>
    </div>
    {% endfor%}
  </div>
</div>
<script src="{% static 'js/recommend.js' %}" type="text/javascript"></script>
{% endblock %}

engage/templates/goal/register.html
{% extends 'base.html' %} {% block styles %} {% load static %}
<link rel="stylesheet" href="{% static 'css/register.css' %}" />
{% endblock %} {% block content %}
<section>
  <div class="mt-4 container-fluid md-4">
    <div class="row">
      <div class="col-md-10 m-auto">
        <div class="card">
          <div class="card-header">
            <h3 class="text-center">Register</h3>
          </div>
          <div class="card-body">
            <h5 class="card-title">Please enter personal information</h5>
            <form
              class="row g-3"
              method="post"
              action="{% url 'movies:register' %}"
            >
              {% csrf_token %}
              <div class="col-md-6">
                <label for="inputFirstName" class="form-label"
                  >First Name</label
                >
                <input
                  type="text"
                  class="form-control"
                  id="inputFirstName"
                  name="first_name"
                  placeholder="Enter First Name"
                />
              </div>
              <div class="col-md-6">
                <label for="inputLastName" class="form-label">Last Name</label>
                <input
                  type="text"
                  class="form-control"
                  id="inputlastName"
                  name="last_name"
                  placeholder="Enter Last Name"
                />
              </div>
              <div class="col-md-12">
                <label for="inputEmail4" class="form-label">Email</label>
                <input
                  type="email"
                  class="form-control"
                  id="inputEmail4"
                  name="email"
                  placeholder="Enter Email"
                />
              </div>
              <div class="col-md-6">
                <label for="inputUserName" class="form-label">Username</label>
                <input
                  type="text"
                  class="form-control"
                  id="inputUserName"
                  name="username"
                  placeholder="Enter Username"
                />
              </div>
              <div class="col-md-6">
                <label for="inputPassword4" class="form-label">Password</label>
                <input
                  type="password"
                  class="form-control"
                  id="inputPassword4"
                  name="password"
                  placeholder="Enter Password"
                />
              </div>
              <div class="col-md-4">
                <label for="inputDate" class="form-label">Date of Birth</label>
                <input
                  type="date"
                  class="form-control"
                  id="inputDate"
                  name="dob"
                />
              </div>
              <h6 class="mt-4 card-subtitle mb-2 text-muted">
                Please enter contact details
              </h6>
              <div class="col">
                <label for="inputPhone" class="form-label">Phone Number</label>
                <input
                  type="text"
                  class="form-control"
                  id="inputPhone"
                  placeholder="Phone Number"
                  name="phone"
                />
              </div>
              <div class="col">
                <label for="inputCity" class="form-label">City</label>
                <input
                  type="text"
                  class="form-control"
                  id="inputCity"
                  placeholder="City"
                  name="city"
                />
              </div>
              <div class="col">
                <label for="inputCountry" class="form-label">Country</label>
                <input
                  type="text"
                  class="form-control"
                  id="inputCountry"
                  placeholder="Country"
                  name="country"
                />
              </div>

              <div class="col-12">
                <div class="form-check">
                  <input
                    class="form-check-input"
                    type="checkbox"
                    id="gridCheck"
                  />
                  <label class="form-check-label" for="gridCheck">
                    Agree to the terms and usage. We may use your data for
                    scientific research.
                  </label>
                </div>
              </div>
              <div class="col-12">
                <button type="submit" class="btn btn-primary">Sign in</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

engage/templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'movies:index' %}">Your Goal</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/goal/">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Moods
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="/goal/?mood=happy">Happy!</a></li>
            <li><a class="dropdown-item" href="/goal/?mood=surprised">Surprised!</a></li>
            <li><a class="dropdown-item" href="/goal/?mood=sad">Sad</a></li>
            <li><a class="dropdown-item" href="/goal/?mood=neutral">Neutral</a></li>
            <li><a class="dropdown-item" href="/goal/?mood=fearful">Fearful</a></li>
            <li><a class="dropdown-item" href="/goal/?mood=angry">Angry</a></li>
            <li><a class="dropdown-item" href="/goal/?mood=disgusted">Disgusted</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            More
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'movies:location' %}">In your location</a></li>
            <li><a class="dropdown-item" href="#searchBox">Your favourite actor</a></li>
            <li><hr class="dropdown-divider" /></li>
            <li><a class="dropdown-item" href="{% url 'movies:index' %}">Let us detect your mood!</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex me-4" method="post" action="{% url 'movies:search' %}">
        {% csrf_token %}
        <div class="input-group">
          <div class="input-group-text" id="basic-addon2">
            Search
          </div>
          <input
            id="searchBox"
            class="form-control me-2"
            name="searchString"
            type="search"
            aria-label="Search"
            aria-describedby="basic-addon2"
          />
        </div>
      </form>
      {% if user.is_authenticated %}
      <div class="navbar-nav me-2 mb-2 mb-lg-0">
        <div class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            {{ user.get_short_name }}
          </a>
          <ul
            class="dropdown-menu dropdown-menu-end navbar-dropdown-user"
            aria-labelledby="navbarDropdown"
          >
            <li>
              <div class="container-fluid">
                <div class="row">
                  <div class="col-lg-4">
                    <img
                      class="img-fluid rounded-circle"
                      src="https://i.pravatar.cc/200"
                      alt="{{ user.get_short_name }}"
                    />
                  </div>
                  <div class="col-lg-8">
                    <span class="text-left"><strong>{{ user.get_full_name }}</strong></span>
                    <span class="text-left small">{{ user.email }}</span><br/><br/>
                    <p class="text-left">
                      <a href="{% url 'movies:logout' %}" class="btn btn-secondary btn-block btn-sm w-100">Logout</a>
                    </p>
                </div>
              </div>
            </li>
            <!-- <li><hr class="dropdown-divider" /></li>
            <li>
              <a class="dropdown-item" href="{% url 'movies:logout' %}"
                >Logout</a
              >
            </li> -->
          </ul>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
</nav>